[project]
name = "django-mini"
version = "0.1.0"
description = "Django Mini Project"
requires-python = ">=3.13"
dependencies = [
    "django==5.2.8",
    "gunicorn==23.0.0",
    "psycopg[binary]>=3.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
